### ISSUE TITLE
ZeroDivisionError if you give size <100

### ISSUE THREAD

**Issue by eggplants** [damianrusinek/zip-bomb#4]
This code will cause `ZeroDivisionError` if you give `size < 100`.
```bash
$ python zip-bomb.py flat 99 out.zip
```
Ref:
https://github.com/damianrusinek/zip-bomb/blob/24bc0c6ca008814b33df32fe6aa7046fecc56e36/zip-bomb.py#L49

You should:
https://stackoverflow.com/questions/14117415/in-python-using-argparse-allow-only-positive-integers

**Comment by damianrusinek** [comment]
Thanks for fix. Change the PR from Draft to Ready whenever you are ready :)

**Comment by eggplants** [comment]
Just changed
